### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by lq-259** [txperl/JustList#32]
root@localhost:~/JustList# python3 main.py                                                        [Altfe] ;)
[cache] running                                                                                   Traceback (most recent call last):
  File "main.py", line 49, in <module>
    bridge.bridgeInit().run(hint=True)                                                              File "/root/JustList/altfe/bridge.py", line 30, in run
    classRoot.instantiate(["LIB_INS"])                                                              File "/root/JustList/altfe/interface/root.py", line 57, in instantiate
    cls.__MODULE[key][name] = cls.__MODULE[key][name]()                                             File "/root/JustList/app/lib/ins/conf/main.py", line 14, in __init__
    self.load_config()                                                                              File "/root/JustList/app/lib/ins/conf/main.py", line 27, in load_config
    self.dict(fileName_, wrapper=True, reload=True)                                                 File "/root/JustList/app/lib/ins/conf/main.py", line 47, in dict
    for key in defaultDic.format2flat():
  File "/root/JustList/app/lib/ins/conf/wrapper.py", line 41, in format2flat                          r.update(self.format2flat(item, finalKeys + [key]))
  File "/root/JustList/app/lib/ins/conf/wrapper.py", line 39, in format2flat                          r.update({".".join(finalKeys + [key]): item})
TypeError: sequence item 1: expected str instance, int found
![Screenshot_20211130-161341~2](https://user-images.githubusercontent.com/60541200/144020912-cac971ad-3d09-487e-92fa-c49fac23bf35.png)
![Screenshot_20211130-161408](https://user-images.githubusercontent.com/60541200/144020981-7f323dec-b32c-4940-b60b-8a363d502b46.png)
![Screenshot_20211130-161356](https://user-images.githubusercontent.com/60541200/144021019-b80014f1-f094-4a71-ab20-c6069e287d98.png)
![Screenshot_20211130-161316](https://user-images.githubusercontent.com/60541200/144021067-0f553a29-3916-48d2-883a-5fda4973adb2.png)
![Screenshot_20211130-161300](https://user-images.githubusercontent.com/60541200/144021110-ec01bab4-598f-430f-b73f-de39863d79dd.png)
不知道是哪里的问题

**Comment by txperl** [comment]
把所有纯数字的账户名用双引号包裹就好了。如下：

```yaml
# cloud189
accounts:
  "147":
    - ...
    - ...
  "153":
    - ...
    - ...
```

这是一个程序 BUG，已经部分修复了，后续会对其他部分进行优化。

但为了避免其他可能的问题，建议还是采取上面的方法。

**Comment by lq-259** [comment]
> 把所有纯数字的账户名用双引号包裹就好了。如下：
> 
> ```yaml
> # cloud189
> accounts:
>   "147":
>     - ...
>     - ...
>   "153":
>     - ...
>     - ...
> ```
> 
> 这是一个程序 BUG，已经部分修复了，后续会对其他部分进行优化。
> 
> 但为了避免其他可能的问题，建议还是采取上面的方法。

已经启动了，但好像是缓存有点慢，好几个小时了了一个文件都没显示

**Comment by txperl** [comment]
应该是有很多文件夹？

JustList 会一次性加载所有文件，所以文件层级较多时加载速度会很慢...

**Comment by lq-259** [comment]
> 应该是有很多文件夹？
> 
> JustList 会一次性加载所有文件，所以文件层级较多时加载速度会很慢...

![Screenshot_20211203-195916](https://user-images.githubusercontent.com/60541200/144599127-bef1a0ab-880a-48e8-a8ec-a1de42bcb502.png)
![Screenshot_20211203-195927](https://user-images.githubusercontent.com/60541200/144599183-c7f80c0a-642b-4348-9050-6fffb2b18251.png)
里面有3t的文件，层级倒是不多，就这样不动了

**Comment by txperl** [comment]
等之后我再优化一下吧...

**Comment by nameyou486** [comment]
好像我也遇到这个问题，也是进行到他这一步，9T的文件数量（

**Comment by txperl** [comment]
> 好像我也遇到这个问题，也是进行到他这一步，9T的文件数量（

（（

近期会更新新的加载模式的。
